# Button
control.button.default=BUTTON
control.button.ok=OK
control.button.cancel=CANCEL
control.button.confirm=CONFIRM
control.button.export=EXPORT
control.button.separate=SEPARATE >>
control.button.collect=<< COLLECT
# TextField
control.text-field.default=Text field
control.text-field.prompt-text.path.file.data.collect=Collected test cases file path
control.text-field.prompt-text.path.folder.data.separate=Test cases folder path
# Tooltip
control.tooltip.default=Tooltip
control.tooltip.file.load=Load file
control.tooltip.directory.load=Load directory
# Label
control.label.default=Label
control.label.title=Title
control.label.body=Body
control.label.alert=Alert
control.label.export.to=Export to
control.label.confirm=Confirmation
control.label.input=Input
control.label.output=Output
control.label.wait.please=Please wait ...
control.label.case.test=Test cases
# MenuBar
control.menu.bar.file=File
control.menu.bar.edit=Edit
control.menu.bar.help=Help
# MenuBar Item
control.menu.item.import.file=Import File
control.menu.item.import.folder=Import Folder
control.menu.item.close=Close
control.menu.item.about=About
# RadioButton
control.radio-button.file.excel=Single excel sheet
control.radio-button.file.io=Input output files