# Load file exceptions
exception.file.load=Failed to load excel file
exception.file.empty=The selected file is empty
exception.file.unsupported=Unsupported extension file
exception.file.input.load=Failed to load input data file
exception.file.output.load=Failed to load output data file
# Load directory exceptions
exception.directory.load=Loading directory process failed
exception.directory.empty=The selected directory is empty
exception.directory.files.io.unequal=Unequal number of input and output files
